# -*- coding: utf-8 -*-
"""Riset Prediksi Saham.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDVkIlrWdCVaGOEsX5PO0mlaJM-FLLKr
"""

# Instalasi pustaka yfinance (wajib dijalankan pertama kali di Colab)
!pip install yfinance

# Impor pustaka dasar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

# Impor pustaka Scikit-Learn
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Impor pustaka TensorFlow & Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Mengatur seed untuk reprodusibilitas
np.random.seed(42)
tf.random.set_seed(42)

print("✅ Semua pustaka berhasil diimpor!")

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

ticker_symbol = "BSSR.JK"
data_saham = yf.download(ticker_symbol, start="2018-01-01")
data_saham = data_saham.dropna()

series_harga = data_saham['Close'].values.reshape(-1, 1)
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(series_harga)

# Meningkatkan lookback ke 100 hari untuk konteks lebih dalam
lookback = 100
X, y = [], []
for i in range(lookback, len(scaled_data)):
    X.append(scaled_data[i-lookback:i, 0])
    y.append(scaled_data[i, 0])

X, y = np.array(X), np.array(y)
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
print(f"✅ Data siap: {len(X_train)} sampel dengan lookback {lookback} hari.")

model = Sequential()

# --- Bagian CNN ---
# Conv1D dengan L2 Regularization
model.add(Conv1D(
    filters=64,
    kernel_size=3,
    activation='relu',
    input_shape=(lookback, 1),
    kernel_regularizer=regularizers.l2(0.01)
))
model.add(BatchNormalization())
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.2))

# --- Bagian LSTM ---
# LSTM dengan L2 Regularization pada kernel dan recurrent
model.add(LSTM(
    units=50,
    return_sequences=False,
    kernel_regularizer=regularizers.l2(0.01),
    recurrent_regularizer=regularizers.l2(0.01)
))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# --- Bagian Output ---
model.add(Dense(units=1))

# Kompilasi dengan learning rate awal yang lebih kecil
optimizer_improved = Adam(learning_rate=0.0005)
model.compile(optimizer=optimizer_improved, loss='mean_squared_error')

model.summary()

# Callback untuk optimasi otomatis
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=1e-6, verbose=1)

# Fit model
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

# Visualisasi Kurva Loss
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Train Loss', color='blue')
plt.plot(history.history['val_loss'], label='Val Loss', color='orange')
plt.title(f'Evaluasi Training: {ticker_symbol}')
plt.yscale('log')
plt.legend()
plt.grid(True)
plt.show()

print(f"Melakukan prediksi pada data test untuk {ticker_symbol}...")
predictions = model.predict(X_test)

# Denormalisasi ke nilai Rupiah
predictions_actual = scaler.inverse_transform(predictions)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Kalkulasi Metrik
rmse = np.sqrt(mean_squared_error(y_test_actual, predictions_actual))
mae = mean_absolute_error(y_test_actual, predictions_actual)

print(f"\n=== HASIL EVALUASI MODEL {ticker_symbol} ===")
print(f"Root Mean Squared Error (RMSE) : Rp {rmse:.2f}")
print(f"Mean Absolute Error (MAE)       : Rp {mae:.2f}")

# Visualisasi Prediksi vs Aktual
plt.figure(figsize=(14, 7))
plt.plot(y_test_actual, color='blue', label=f'Harga Aktual {ticker_symbol}')
plt.plot(predictions_actual, color='red', linestyle='--', label='Prediksi Model')
plt.title(f'Perbandingan Harga Aktual vs Prediksi Saham {ticker_symbol}')
plt.xlabel('Hari Pengujian')
plt.ylabel('Harga Saham (IDR)')
plt.legend()
plt.grid(True)
plt.show()



# Menentukan jumlah hari ke depan yang ingin diprediksi
future_days = 7

# Mengambil 100 hari terakhir dari data yang sudah dinormalisasi (scaled_data)
last_100_days = scaled_data[-lookback:]
current_batch = last_100_days.reshape(1, lookback, 1)

future_predictions_scaled = []

print(f"Memproses prediksi {ticker_symbol} untuk {future_days} hari ke depan...")

# Loop rekursif: Prediksi -> Masukkan hasil prediksi ke input -> Prediksi lagi
for i in range(future_days):
    next_pred = model.predict(current_batch, verbose=0)
    future_predictions_scaled.append(next_pred[0, 0])
    next_pred_reshaped = next_pred.reshape(1, 1, 1)
    current_batch = np.append(current_batch[:, 1:, :], next_pred_reshaped, axis=1)

# Denormalisasi hasil prediksi masa depan kembali ke format Rupiah
future_predictions_actual = scaler.inverse_transform(np.array(future_predictions_scaled).reshape(-1, 1))

# Membuat list tanggal untuk hari bursa ke depan
last_date = data_saham.index[-1]
future_dates = pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=future_days)

# Menampilkan hasil prediksi dalam bentuk angka
print(f"\n=== PREDIKSI HARGA SAHAM {ticker_symbol} UNTUK {future_days} HARI BURSA KE DEPAN ===")
for i in range(future_days):
    print(f"Tanggal: {future_dates[i].strftime('%Y-%m-%d')} | Prediksi Harga: Rp {future_predictions_actual[i][0]:.2f}")

# VISUALISASI PENGGABUNGAN DATA HISTORIS DAN MASA DEPAN
last_30_actual = scaler.inverse_transform(scaled_data[-30:])
last_30_dates = data_saham.index[-30:]

plt.figure(figsize=(12, 6))
plt.plot(last_30_dates, last_30_actual, color='blue', label=f'Harga Aktual {ticker_symbol} (30 Hari Terakhir)')

# Menghubungkan titik terakhir aktual dengan prediksi
combined_dates = [last_30_dates[-1]] + list(future_dates)
combined_prices = [last_30_actual[-1][0]] + list(future_predictions_actual.flatten())

plt.plot(combined_dates, combined_prices, color='orange', linestyle='--', marker='o', label=f'Proyeksi {future_days} Hari Kedepan')

plt.title(f'Proyeksi Harga Saham {ticker_symbol} {future_days} Hari Kedepan')
plt.xlabel('Tanggal')
plt.ylabel('Harga Saham (IDR)')
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import ipywidgets as widgets
from IPython.display import display, clear_output
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

# Inisialisasi Widget
ticker_input = widgets.Text(value=ticker_symbol, description='Ticker:', placeholder='Contoh: BBCA.JK')
days_slider = widgets.IntSlider(value=7, min=1, max=30, step=1, description='Hari Prediksi:')
run_button = widgets.Button(description="Jalankan Prediksi", button_style='success', icon='play')
output_area = widgets.Output()

def run_app(b):
    with output_area:
        clear_output()
        symbol = ticker_input.value.upper()
        n_days = days_slider.value

        print(f"🚀 Mengambil data terbaru untuk {symbol}...")

        try:
            # 1. Ambil Data (Tanpa parameter verbose agar kompatibel dengan versi terbaru yfinance)
            df = yf.download(symbol, start="2020-01-01")
            if df.empty or len(df) < 60:
                print(f"❌ Data tidak cukup atau ticker {symbol} tidak valid.")
                return

            # 2. Skalasi Data Lokal
            local_scaler = MinMaxScaler(feature_range=(0, 1))
            close_prices = df['Close'].values.reshape(-1, 1)
            scaled = local_scaler.fit_transform(close_prices)

            # 3. Prediksi Masa Depan
            lb = 60
            current_batch = scaled[-lb:].reshape(1, lb, 1)
            preds_scaled = []

            for _ in range(n_days):
                nxt = model.predict(current_batch, verbose=0)
                preds_scaled.append(nxt[0,0])
                current_batch = np.append(current_batch[:, 1:, :], nxt.reshape(1,1,1), axis=1)

            preds_actual = local_scaler.inverse_transform(np.array(preds_scaled).reshape(-1, 1))

            # 4. Visualisasi Hasil
            f_dates = pd.bdate_range(start=df.index[-1] + pd.Timedelta(days=1), periods=n_days)
            plt.figure(figsize=(12, 5))

            # Plot Data Historis
            plt.plot(df.index[-30:], df['Close'].values[-30:], label='Harga Aktual (30 Hari Terakhir)', color='blue', linewidth=2)

            # Gabungkan titik terakhir dengan prediksi untuk kontinuitas visual
            last_date = df.index[-1]
            # Ambil nilai terakhir dengan aman
            last_val = float(df['Close'].iloc[-1])

            comb_dates = [last_date] + list(f_dates)
            comb_vals = [last_val] + list(preds_actual.flatten())

            plt.plot(comb_dates, comb_vals, 'r--o', label=f'Proyeksi {n_days} Hari ke Depan')

            plt.title(f"Prediksi Tren Harga: {symbol}", fontsize=14)
            plt.ylabel("Harga (IDR)")
            plt.legend()
            plt.grid(True, linestyle=':', alpha=0.6)
            plt.xticks(rotation=45)
            plt.show()

            print(f"✅ Berhasil menganalisis {symbol}.")

        except NameError:
            print("⚠️ Error: Model Deep Learning belum siap. Pastikan sel pelatihan di atas sudah selesai.")
        except Exception as e:
            print(f"⚠️ Kendala teknis: {str(e)}")

run_button.on_click(run_app)
display(widgets.VBox([ticker_input, days_slider, run_button, output_area]))

"""### Menyimpan Model ke Google Drive
Hubungkan Google Drive untuk menyimpan file model secara permanen.
"""

from google.colab import drive
import os

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Tentukan path penyimpanan
save_path = f'/content/drive/MyDrive/MODEL_TRAINNED/SAHAM/model_saham_{ticker_symbol.replace(".", "_")}.h5'

# 3. Simpan model
try:
    model.save(save_path)
    print(f"✅ Model berhasil disimpan di: {save_path}")
except Exception as e:
    print(f"❌ Gagal menyimpan model: {str(e)}")



